### ISSUE TITLE
【HK】支持TVB/MyTVSuper元数据抓取

### ISSUE THREAD

**Issue by SoTender** [fzlins/TMDB-Import#11]
抓取TVB/MyTVSuper官网的官方信息，并将繁体转换为简体。

例子：

状王之王

TVB:
https://programme.tvb.com/tc/justicesungbegins_140304

MyTVSuper:
https://www.mytvsuper.com/tc/programme/justicesungbegins_140304/%E7%8B%80%E7%8E%8B%E4%B9%8B%E7%8E%8B/?utm_source=tvbcompp&utm_medium=episode&utm_campaign=episode_image

区别在于TVB的图片是500+；MyTVSuper的图片是700+（应该能直接拉伸到1280）
还有就是TVB有分集标题和分集简介；MyTVSuper好像只有标题，不知道api能不能看到分集剧情。

但是它们似乎都是用的同一个id:
justicesungbegins_140304

**Comment by fzlins** [comment]
https://marketplace.visualstudio.com/items?itemName=mollykannn.vscode-chinese-translator
简繁转换用这个吧
