### ISSUE TITLE
urllib3.exceptions.ProxySchemeUnknown

### ISSUE THREAD

**Issue by DolbyCoder** [fzlins/TMDB-Import#17]
Python版本3.12
使用过程中出现
python -m tmdb-import "https://www.themoviedb.org/tv/119960/season/1?language=zh-CN"

.\Python\Python312\site-packages\urllib3\poolmanager.py", line 567, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://

**Comment by fzlins** [comment]
试试升级一下pip3 install --upgrade requests
