### ISSUE TITLE
Netflix 的標題問題

### ISSUE THREAD

**Issue by Enterpr1se** [fzlins/TMDB-Import#18]
不少 Netflix 的劇集標題都會有重覆情況
例如 "第 2 集。第 2 集" 這樣
如果可以自動去除 "第 2 集。" 就好了

**Comment by fzlins** [comment]
给个链接，我看看是什么样子的

**Comment by Enterpr1se** [comment]
例子: https://www.netflix.com/hk/title/81749231

<img width="589" alt="螢幕擷取畫面 2024-06-10 203025" src="https://github.com/fzlins/TMDB-Import/assets/5927279/1fa9cc15-63bd-4cd7-970d-6cfca2b70f7a">
