### ISSUE TITLE
功能反馈：能加个自动在自己的视频资源截分集剧照吗？

### ISSUE THREAD

**Issue by CeRu-007** [fzlins/TMDB-Import#21]
类似于：一集截一张不带字幕的图，有些维护的剧集在流媒体平台下架了没数据，也有些剧集官网上都是带字幕的图，这种时候缺个能自动截图并上传的功能了

**Comment by fzlins** [comment]
随机截图质量太差，没有必要

**Comment by CeRu-007** [comment]
或者换个思路，对自己的影视资源每一集截取一定（自定义）数量的图片，每一集我们再保留没字幕质量好的那张，再批量上传。相关构思：每一集对应一个文件夹，假如第一集的文件夹里生成了按序号排列的5张图片，脚本的话输入对应的序号代表上传哪张图，然后默认每一集的序号都是1，如果其中哪一集有带字幕的图，就可以换另一张图的序号来决定上传哪张，这样可以大大提高效率。大佬看我这次这个想法行不行得通？
