### ISSUE TITLE
可以支持下Disney+选择季度吗

### ISSUE THREAD

**Issue by ltsj** [fzlins/TMDB-Import#3]
目前似乎只支持最新季的信息

**Comment by fzlins** [comment]
> 目前似乎只支持最新季的信息

我测试一下，可以给一个例子吗？

**Comment by ltsj** [comment]
大佬这么晚了 还在 哈哈 打扰了
链接：
https://www.disneyplus.com/zh-hans/series/the-simpsons/3ZoBZ52QHb4x
import.csv：
episode_number,name,air_date,runtime,overview,backdrop
S34E1,失踪的乌龟,2022-09-25,22,霍默在一次镇民大会上颇为丢脸，后来为重新被大家接纳，他加入了一个寻找失踪乌龟的互联网团体，但却发现了更邪恶的东西。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/ADBC1C4D748CCBECB6CEFD75540117DE24E301D9826213165FE6545EFA770320
S34E2,愤怒的丽莎,2022-10-02,22,丽莎被要求担任陪审员，而麦琪则痴迷于她的健身脚踏车。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E2E04E393FC1B73D1E36D77679927BCE433504721004124B9949CA3B4DC6C101
S34E3,童子军丽莎,2022-10-09,22,男孩探险队开始接收女生，巴特和丽莎发誓要在一年一度的狂欢节上“完胜”对方。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C623003A38FB61296009EF00873F304B548CC21BB3252DE4C6FDEC8BF5AD5E4A
S34E4,好人之王,2022-10-16,22,玛姬被聘为克里斯蒂的新日间脱口秀的环节制作人。但当她发现这份工作其实是一场无尽的噩梦时，她最初的兴奋感随之消散殆尽。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/B71FCB76BB2416AEC764270654244198414C9CD6AA3D945AFF22050C8AB73E4D
S34E5,《不是它》,2022-10-23,22,在这个万圣节《恐怖树屋》剧集里，荷马和他的少年朋友被一个小丑追杀，滑稽模仿斯蒂芬·金的小说《它》。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/422718FA6B792AF01747CA96717829ABF77A496347C4C6A9EFF2E1883695FF6D
S34E6,《恐怖树屋 第33集》,2022-10-30,23,在以书为主题的三部曲中，玛吉心生可怕的怨恨，丽莎企图以杀戮拯救地球，而荷马得知他不是他所认为的那个样子。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/EBDEFF96A92030353012FD35EBCE8034B1206DD4876961D8E3713B63C91FA725
S34E7,从啤酒到亲子关系,2022-11-13,22,当荷马成为达夫曼的奶爸英雄时，他们和丽莎进行了一次公路旅行，这可能会暴露荷马糟糕的育儿方式。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/37BACE75D6A76D60E4CCF53B94E6250E25120E07D3A2192B4DC5C170FF8B10DC
S34E8,同一星球的后弟弟,2022-11-20,22,当爷爷成了荷马女朋友的古怪的小儿子的宠溺的继父时，他的愤怒和怨恨让他自己大为震惊。丽莎和巴特办了一场终极睡衣派对。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6BB6A7F9D531ED971E860D40C86BB3D21F71E240150C1CF981E68DC2C81D4369
S34E9,尼尔森与丽莎的相遇,2022-11-27,22,斯普林菲尔德最不般配情侣的让人完全摸不到头脑的未来故事。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/61D14E0819028BB71CECB30CFD47F0D989250EC250624D3836D1709D5E4C7D47
S34E10,不一样的游戏,2022-12-04,22,"巴特在网络游戏中发现一个有利可图的故障,他诱骗斯金纳校长进入了他利润丰厚的犯罪事业。玛吉和麦琪发现了天堂。",https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A06A2CEE8938E37A4C696140E8065D6A406A96547C34C005A91C50946DD71137
S34E11,高端操作,2022-12-11,22,"莫伊教练招募了世界上最伟大的拳击手来教尼尔森曲棍球进攻的艺术,《辛普森一家》的粉丝们被35年来第二次曲棍球主题的剧集激怒了。",https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A7903C88027574C87437A997F92382E0E7A3D1EDC24C5F99AD29647EEC4D00B1
S34E12,我的生活视频博客,2023-01-01,22,通过油管上的一系列推广视频，展现辛普森一家酸甜苦辣的视频博客开始发布。,https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/56A74DE139E683ED4DEE804E88B02E0753D52FEFF627A112043568DDCCA9A441

**Comment by fzlins** [comment]
试一下，应该可以抓到全部了。

**Comment by ltsj** [comment]
可以了 牛👍 去搬信息了
