### ISSUE TITLE
关于图片分辨率过低被跳过的问题⭐

### ISSUE THREAD

**Issue by SoTender** [fzlins/TMDB-Import#6]
VIU等图片分辨率过低被跳过的问题

例子：
基督山小姐
https://www.themoviedb.org/tv/116671/seasons
python -m tmdb-import "https://www.viu.com/ott/sg/zh/vod/336636"
python -m tmdb-import "https://www.themoviedb.org/tv/116671/season/1?language=zh-CN"

感觉这个我可以自己手动修改代码里的最低分辨率要求实现。
但是我没有去看代码，不用更新，告诉在哪儿手动调就好了。

【亟待解决程度：⭐】

**Comment by fzlins** [comment]
https://github.com/fzlins/TMDB-Import/blob/master/tmdb-import/processors/image.py
第51行
