### ISSUE TITLE
关于下架剧集⭐

### ISSUE THREAD

**Issue by SoTender** [fzlins/TMDB-Import#7]
例子：

奇异果子🥝：
致命游戏
https://www.iqiyi.com/v_292ufskwxxo.html
python -m tmdb-import "https://www.iqiyi.com/v_292ufskwxxo.html"

裤子👖：
后宫开挂人生
https://v.youku.com/v_show/id_XNjAyMjgxODQ2NA==.html
python -m tmdb-import "https://v.youku.com/v_show/id_XNjAyMjgxODQ2NA==.html"

有办法抓取信息嘛

【亟待解决程度：⭐】

**Comment by fzlins** [comment]
无法实现。可以去其它平台抓取。
